### ISSUE TITLE
Dependencies issue ?

### ISSUE THREAD

**Issue by nouryf** [tobinbradley/timemachine#1]
Hi,

I was able to take a look at the viewer from your blog post. Gool stuff and thanks for sharing the code here at Github.

I cloned the repo and tried to build it. I have npm and yarn installed on my CentOS7 machine.
Running `npm install` produces the following:
```
─┬ @mapbox/mapbox-gl-geocoder@2.2.0  (git+https://github.com/tobinbradley/mapbox-gl-geocoder.git#4baf26bdecfcbe2d2afaebb4be816eb9d5c0f575)
│ ├─┬ global@4.3.2 
│ │ ├─┬ min-document@2.19.0 
│ │ │ └── dom-walk@0.1.1 
│ │ └── process@0.5.2 
│ ├── lodash.debounce@4.0.8 
│ ├── promise-polyfill@7.1.2 
│ ├─┬ suggestions@1.3.3 
│ │ └── fuzzy@0.1.3 
│ └── whatwg-fetch@2.0.4 
└── UNMET PEER DEPENDENCY mapbox-gl@0.44.2

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.1.2 (node_modules/postcss-cli/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.1.2 (node_modules/watchpack/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN mapbox-gl-compare@0.1.0 requires a peer of mapbox-gl@0.26.0 but none was installed.
npm WARN timemachine@1.0.0 No repository field.
```

I noticed it's complaining about different versions on Mapbox-gl (0.44.2 and 0.26.0).
I must be missing some thing on how to build it. Can you please help ?

One the dependencies is resolved, one would just run `yarn build` to build it ? or a different step is involved ?
 
Thanks

**Comment by tobinbradley** [comment]
Sorry - I'd say the documentation was bad, but that would imply there was documentation :).

Do a git pull and it will grab a new README (and fix a CSS bug). The yarn warnings are about some dependencies asking for different versions of some libraries and doesn't cause any problems.

`yarn start` will start the site locally on your machine with live reload for development. `yarn run build` will build the site for production, minimizing and uglifying and tree shaking. The stuff generated will be in the `dist` folder.

Hope that helps!

**Comment by nouryf** [comment]
Hi,

I did `git pull`, got latest and followed guideline to build it. The `dist` folder was created with bundled components. The .html displays ok and viewer is working just fine. It's great. Thanks for your quick response, help and for sharing this cool app.

**Comment by nouryf** [comment]
If i may ask do you know where i can get some sample aerial images may be for a small area covering 2 or 3 years, to go through the process of creating tiles from start and serving the way you did ?

Thanks again

**Comment by tobinbradley** [comment]
It depends on the area/year/resolution you're looking for. There isn't a central index for this stuff that I'm aware of, so you will probably have to dig around on google.

You could always grab Landsat imagery. It goes back a ways.
https://gisgeography.com/usgs-earth-explorer-download-free-landsat-imagery/

**Comment by tst-nfarah** [comment]
Thanks !

**Comment by nouryf** [comment]
thank you
