### ISSUE TITLE
Boundary line disappears from main map when zooming in time-machine mode

### ISSUE THREAD

**Issue by flott** [tobinbradley/timemachine#4]
This is a really great project, and thanks so much for sharing it on here! I'm new to Svelte and am having some trouble tracking down what might be happening with this issue. When I turn on the time-machine magnifying loop and change the zoom level of the map, the boundary disappears from the main map. It stays on the magnifying-glass map, though, and appears to persist even if it's toggled off and back on again. It doesn't appear to be a browser/OS specific issue for me. Any suggestions? Thanks very much!

**Comment by tobinbradley** [comment]
Huh. Looks like a layer can only be added to one Leaflet map, so when it gets added to the lens map it gets taken off the main map after a zoom.

I just defined the layer twice to fix the problem.  Give it the old git pull and see if it's fixed, or if you've fiddled with Map.svelte all I did was make a second layer:

```javascript
function initMap(node) {
    const boundary = L.geoJSON(geoBoundary, {
      style: {
        fill: false
      }
    })
    const tmBoundary = L.geoJSON(geoBoundary, {
      style: {
        fill: false
      }
    })
```

And use the second one for the magnifying glass:

```javascript
// time machine glass
    magnifyingGlass = magGlass({
      zoomOffset: 0,
      radius: 130,
      boundary: tmBoundary,
```

Thanks for letting me know about the problem!

**Comment by flott** [comment]
Yep, that fixed it for me! I'm excited to play around with this and our King County aerials. Thanks so much!
